version: '3.8'
services:
  app:
    image: spring-boot-practice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/practice
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HIBERNATE_DDL_AUTO=create
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
    ports:
      - "3306:3306"
